### ISSUE TITLE
[Question] Retraining espaloma model to include nonbonded potentials

### ISSUE THREAD

**Issue by niccolo93** [choderalab/espaloma#125]
Hello, I'm trying to retrain espaloma model on my own data and I was wondering how can I extract non bonded potentials. As far as I see in the GitHub repo the code that includes non bonded calculations in `espaloma/mm/energy.py` the application of nonbonded energies is commented out. So my questions are: 

1. How can I do to retrain the model including also non bonded energies calculation?
2. How can I then extract them from the graph after applying the model to a new molecule?

Thanks!

**Comment by yuanqing-wang** [comment]
hi @niccolo93 currently we haven't tested including non-bonded energies in the training yet. but you can define any function forms you wish as long as the features you specify in JanossyPooling https://github.com/choderalab/espaloma/blob/ec45de310836cede8776b426d64d54aad9f9efd1/espaloma/nn/readout/janossy.py#L12 matches the energy functions you write.
