### ISSUE TITLE
Question: example code for setting up MD simulation of protein-ligand complexes

### ISSUE THREAD

**Issue by mganahl** [choderalab/espaloma#135]
Hi!
Thanks for the great work here!

I'm be interested in running an MD simulation of a protein-ligand complex, using espaloma for the ligand FF and a standard FF for the protein (e.g. one of the amber ff). Is there any example code to help me get started? (I'm a newcomer to the field :)!). 

Thanks!

**Comment by yuanqing-wang** [comment]
Hi @mganahl 

Sorry for the delayed response. We are using OpenMMForceFields https://github.com/openmm/openmmforcefields to assign parameters to different regions of protein-ligand complex.
