### ISSUE TITLE
Environment yaml file with explicit versions

### ISSUE THREAD

**Issue by simonaxelrod** [choderalab/espaloma#147]
Hi everyone,

Thanks for the great project and repo! I was wondering if you could provide an environment yaml file that has explicit versions of each package. The reason is that I'm having version trouble with packages like DGL (I get cuda-related errors after building the environment from [this file](https://github.com/choderalab/espaloma/blob/master/devtools/conda-envs/espaloma.yaml); installing dgl-cuda then gives me DGL version 2.X, but the syntax of espaloma seems to only work with DGL version 1.X). I think this should be as easy as taking one of your working espaloma conda environments, and exporting it with `conda env export > environment.yml`.

Thanks!

Simon

**Comment by mikemhenry** [comment]
Hey Simon!

Sorry for taking so long to get back to you. We just released a new version of espaloma that is easier to install with `conda install -c conda-forge -c dglteam "espaloma=0.3.1" "dgl<1"` We are close to getting `dgl` on conda-forge which will make it even easier to install (and support newer `dgl 1.x` code.

**Comment by simonaxelrod** [comment]
No problem! This looks great, thank you :)

**Comment by mikemhenry** [comment]
Let me know if you have any issues getting this working for you :)
