### ISSUE TITLE
Switch to using Read the Docs 

### ISSUE THREAD

**Issue by mikemhenry** [choderalab/espaloma#165]
@kntkb @yuanqing-wang @jchodera 

I was thinking about switching to using read the docs to host `docs.espaloma.org` We can use github pages if you rather. 

One thing I don't understand for the doc building is `download_experiments.sh` is this something that is still needed? The script has some issues and doesn't actually work:

https://github.com/choderalab/espaloma/actions/runs/5524363534/jobs/10076565563#step:5:67
```
2023-07-11 20:15:33 (24.7 MB/s) - ‘typing.ipynb’ saved [6691/6691]

[TerminalIPythonApp] WARNING | Unrecognized alias: 'to', it will have no effect.
[TerminalIPythonApp] WARNING | File 'nbconvert' doesn't exist
mv: cannot stat 'typing.rst': No such file or directory
```

If the goal is to take those notebooks (why are they on google docs and not in the repo?), remove the outputs, then add them to the documentation, I can setup that pipeline. 

Thanks!

**Comment by mikemhenry** [comment]
Pro with RTD: Users can search the docs and we can get a preview of the docs built in the pull request so we can see what it looks like

**Comment by yuanqing-wang** [comment]
Yes I like your idea!yuanqing On Jul 11, 2023, at 7:35 PM, Mike Henry ***@***.***> wrote:﻿
Pro with RTD: Users can search the docs and we can get a preview of the docs built in the pull request so we can see what it looks like

**Comment by ijpulidos** [comment]
This one should be solved by https://github.com/choderalab/espaloma/pull/167 . Closing.
