### ISSUE TITLE
avoid pydantic 2

### ISSUE THREAD

**Issue by chrisiacovella** [choderalab/espaloma#170]
Version 2 of pydantic seems to break any code using v1.  The conda-feedstock and dev environment yaml files should be update to ensure using <2.

**Comment by mikemhenry** [comment]
We **should** be okay since we don't actually have `pydantic` as a dependency. 

```
$ grep -r "pydantic"
scripts/perses-benchmark/espaloma-perses.export.yaml:  - pydantic=1.9.0=py39hb9d737c_1
```

The only hit looks like an export of a yaml that would include the entire environment.

**Comment by chrisiacovella** [comment]
I think this issue might come from packages espaloma depends on that don't adequately pin versions.   A quick `mamba install espaloma` has it trying to install 2.0.2:

`  + pydantic                            2.0.2  py310h2aa6e3c_1          conda-forge     517kB`

**Comment by mikemhenry** [comment]
Resolved in #172

**Comment by chrisiacovella** [comment]
It looks like they updated it 2 weeks ago to require less <2.  So the behavior is strange. 

If I `conda install qcelemental`, it will grab the most current version (qcelemental-0.25.1-pyhd8ed1ab_2) with the pinned pydantic version. 

If I `conda install espaloma`  or `conda install qcportal`(as qcelemental is a dependency) it will grab the 8 month old version (qcelemental-0.25.1-pyhd8ed1ab_1) and pydantic 2.0.2

So it looks like the issue is that qcportal doesn't have a max version of pydantic.   I'm still very new to dealing with the Conda-forge feedstocks, so is behavior (ignoring dependency limits) pretty, uh, typical?  

If I added qcelemental before qcportal in the espaloma environment file, I get the correct behavior.  So is this basically just an order operations issue?  the qcportal feedstock has pydantic first...so it install pydantic 2, and realizes it can resolve the conflict in qcelemental by grabbing the older version?

    - pydantic >=1.4
    - qcelemental >=0.13.1

**Comment by chrisiacovella** [comment]
I just submitted an issue to qcportal, so hopefully they will resolve (either pinning or changing the order of dependencies in the meta.yaml).  Thanks for your input @mikemhenry

**Comment by mikemhenry** [comment]
Keeping it open is nice as well since if someone searches for this issue they might find it and see we are working on it.

**Comment by mikemhenry** [comment]
Can you link the qcportal issue here?

**Comment by chrisiacovella** [comment]
Link to relevant qcportal issue:

https://github.com/choderalab/download-qca-datasets/issues/1

**Comment by mikemhenry** [comment]
Good call btw in getting that pin into our own feedstock since upstream hasn't fixed it yet :+1:

**Comment by mattwthompson** [comment]
Recommend anywhere in your source code using

```python
try:
    from pydantic.v1 import BaseModel
except ImportError:
    from pydantic import BaseModel
```

as this allows the same code to work with both installed versions. OpenFF is rolling out this change after seeing Levi and Lori do it in the QCArchive stack. Downsides are 
* requires pushing out new versions and builds
* doesn't leverage v2 improvements, pushes the refactor into the future
* doesn't fix the problem if it's actually in upstreams

https://docs.pydantic.dev/2.0/migration/

**Comment by mikemhenry** [comment]
> doesn't fix the problem if it's actually in upstreams

This is really our current issue since we don't use `pydantic` directly (at least in this repo).

Thanks!

**Comment by ijpulidos** [comment]
As @mikemhenry said, we are not really using pydantic for this code base. Closing. Feel free to reopen if something else comes up related to this. Thanks!
