### ISSUE TITLE
Improved documentation on how to use local model

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/espaloma#182]
It was noted in https://github.com/choderalab/espaloma/issues/181 that loading a model that has been previously downloaded in `.pt` format needs a call to the `eval` method to have correct predictions/inference using the model.

**Comment by mikemhenry** [comment]
Yes I think it could use a mention since this is quite a foot gun, which is why in the quick start we list using the `esp.get_model` function. 

We probably need to grep our examples and snippets and make sure we call `eval()` or use `esp.get_model`

**Comment by ijpulidos** [comment]
I believe only the main `README.md` and the `deploy.rst` files are the ones that should have changes here, as far as I can see. Added the changes for the README file to the PR.
