### ISSUE TITLE
Issue with conda installation

### ISSUE THREAD

**Issue by pmorerio** [choderalab/espaloma#195]
Hi, 
I am experiencing problems in installing with 
`conda install -c conda-forge "espaloma=0.3.2"`
as suggested in the README.

Looks like conda gets stuck in solving the environment (more than a day).
`Solving environment: | `

I tried on 3 different machines and also with different python versions (3.6, 3.7, 3.8, 3.9).

Do you have any suggestion - suggested python version etc.?

**Comment by ijpulidos** [comment]
Interesting, I guess at this point we should just recommend using mamba, instead of conda, that one works for me under Linux and MacOS.

Specifically running `mamba create -n espaloma-032 -c conda-forge espaloma=0.3.2` did it for me. I hope that helps.

**Comment by pmorerio** [comment]
Will try mamba thanks.
Let you know if it works

**Comment by pmorerio** [comment]
Mamba works fine, thank you very much!
