### ISSUE TITLE
Question: what is the script used for training espaloma 0.3.2?

### ISSUE THREAD

**Issue by pmorerio** [choderalab/espaloma#196]
Hi, thank you very much for your work.
I see 4 training scripts used for training in the `espaloma/app` folder.
Which is the one used to train `espaloma 0.3.2`?
Alternatively, could you provide the bash string wit the correct `argparse` parameters?

**Comment by ijpulidos** [comment]
I think the best resource for retraining/refitting espaloma is https://github.com/choderalab/refit-espaloma

**Comment by pmorerio** [comment]
Thanks!

**Comment by mikemhenry** [comment]
I've made a PR here https://github.com/choderalab/espaloma/pull/198/files that adds the recommendation to use mamba. @pmorerio Let me know if that would have helped!

**Comment by pmorerio** [comment]
Thanks @mikemhenry, I think your comment refers to the other issue I recently opened https://github.com/choderalab/espaloma/issues/195#event-10782739631

**Comment by pmorerio** [comment]
Closing since answered by @ijpulidos
